# When including these tasks into a role, the following variables are
# available:
#
# - site_name: set to override the default value of "role_name"
# - site_static: set to true to configure static site hosting
# - site_proxy: set to true to configure basic proxying to another port

# Adds DNS A/AAAA records so that the site is addressable and the name-based
# vhosts function properly
- name: HTTP - Configure Site DNS Records
  ansible.builtin.include_tasks:
    file: ../../dns/tasks/configure-a-records.yml
  vars:
    record: "{{ site_name | default(role_name) }}.{{ domain }}"

# Provisions a TLS certificate to ensure SSL parts function properly
- name: HTTP - Configure Site TLS Certificate
  ansible.builtin.include_tasks:
    file: ../../tls/tasks/configure-cert.yml
  vars:
    cert_name: "{{ site_name | default(role_name) }}"

# This file configures a vhost for the calling role, including all necessary TLS
# moving parts
- name: HTTP - Install Site Virtual Host
  ansible.builtin.template:
    src: ../../http/templates/apache.vhost.conf
    dest: "/etc/httpd/conf.d/vhosts.d/{{ _pri_name }}.conf"
    setype: httpd_config_t
    mode: '0644'
  vars:
    _site: "{{ site_name | default(role_name) }}"
    _pri_name: "{{ (_site == host.name) | ternary('00-' + _site, '10-' + _site) }}"
  notify:
    - Reload Apache

# All templates supplied by the calling role named like "*.apache.conf" will be
# included by the above vhost configuration
- name: HTTP - Ensure Site Config Directory
  ansible.builtin.file:
    state: directory
    path: "/etc/httpd/conf.d/includes.d/{{ site_name | default(role_name) }}"
    mode: '0755'
- name: HTTP - Install Custom Site Config
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/httpd/conf.d/includes.d/{{ site_name | default(role_name) }}/10-{{ item | basename }}"
    setype: httpd_config_t
    mode: '0644'
  with_fileglob:
    - "{{ role_path }}/templates/*.apache.conf"
  notify:
    - Reload Apache
- name: HTTP - Install Static Site Config
  ansible.builtin.template:
    src: "../../http/templates/apache.static.conf"
    dest: "/etc/httpd/conf.d/includes.d/{{ site_name | default(role_name) }}/00-static.conf"
    setype: httpd_config_t
    mode: '0644'
  when: site_static | default(false)
  notify:
    - Reload Apache
- name: HTTP - Install Proxied Site Config
  ansible.builtin.template:
    src: "../../http/templates/apache.proxy.conf"
    dest: "/etc/httpd/conf.d/includes.d/{{ site_name | default(role_name) }}/00-proxy.conf"
    setype: httpd_config_t
    mode: '0644'
  when: site_proxy | default(false)
  notify:
    - Reload Apache

# Static sites require a place from which to serve files
- name: HTTP - Ensure Document Root Directory
  ansible.builtin.file:
    state: directory
    path: "{{ www_root }}/html/{{ site_name | default(role_name) }}"
    mode: '0755'
  when: site_static | default(false)
