- name: Install Apache
  ansible.builtin.dnf:
    name:
      - httpd
      - mod_ssl
    state: present

- name: Create Apache Site Config Directories
  ansible.builtin.file:
    state: directory
    path: "{{ item.path }}"
    seuser: system_u
    setype: httpd_config_t
    mode: '0755'
  loop:
    - { path: /etc/httpd/conf.d/vhosts.d }
    - { path: /etc/httpd/conf.d/includes.d }

- name: Create Apache Web Root Directories
  ansible.builtin.file:
    state: directory
    path: "{{ www_root }}/{{ item }}"
    setype: httpd_sys_content_t
    mode: '0755'
  loop:
    - acme
    - html

- name: Install Main Apache Configuration
  ansible.builtin.template:
    src: httpd.conf
    dest: "/etc/httpd/conf/httpd.conf"
    mode: '0644'
  notify:
    - Reload Apache

- name: Configure SELinux To Allow Proxy Connections
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

# Create self-signed TLS certificates for the host, this allows the httpd
# service to be brought up and real TLS certificates to be requested via
# ACME challenge
- name: Configure Site TLS Self-Signed Certificate
  ansible.builtin.include_tasks:
    file: ../../tls/tasks/configure-cert.yml
  vars:
    cert_name: "{{ host.name }}"
    self_signed_certs: True

# Create a default, catch-all virtual host site
- name: Install Default Virtual Host
  ansible.builtin.template:
    src: apache.vhost-default.conf
    dest: /etc/httpd/conf.d/vhosts.d/00-default.conf
    setype: httpd_config_t
    mode: '0644'
  notify:
    - Reload Apache

- name: Enable/Start Apache
  ansible.builtin.systemd_service:
    name: httpd.service
    enabled: true
    masked: no
    state: started

- name: Open Firewall for HTTP/HTTPS
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - http
    - https
  notify:
    - Reload Firewall

# Replace the self-signed TLS certificates created earlier with real
# certificates
- name: Configure Site TLS Certificate
  ansible.builtin.include_tasks:
    file: ../../tls/tasks/configure-cert.yml
  vars:
    cert_name: "{{ host.name }}"
