- name: Install Apache
  ansible.builtin.dnf:
    install_weak_deps: false
    name:
      - httpd
      - mod_ssl
    state: present

- name: Create Apache Site Config Directories
  ansible.builtin.file:
    state: directory
    path: "{{ item.path }}"
    seuser: system_u
    setype: httpd_config_t
    mode: '0755'
  loop:
    - { path: /etc/httpd/conf.d/vhosts.d }
    - { path: /etc/httpd/conf.d/includes.d }

- name: Create Apache Web Root Directories
  ansible.builtin.file:
    state: directory
    path: "{{ www_root }}/{{ item }}"
    setype: httpd_sys_content_t
    mode: '0755'
  loop:
    - acme
    - html

- name: Install Main Apache Configuration
  ansible.builtin.template:
    src: httpd.conf
    dest: "/etc/httpd/conf/httpd.conf"
    mode: '0644'
  notify:
    - Reload Apache

- name: Configure SELinux To Allow Proxy Connections
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: Open Firewall for HTTP/HTTPS
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - http
    - https

- name: Install HTTP Default Virtual Host
  ansible.builtin.template:
    src: vhost-default-http.conf
    dest: /etc/httpd/conf.d/vhosts.d/00-default.conf
    setype: httpd_config_t
    mode: '0644'
  notify:
    - Reload Apache

- name: Enable/Start Apache
  ansible.builtin.systemd_service:
    name: httpd.service
    enabled: true
    masked: no
    state: started

- name: Configure TLS Certificate for Default Virtual Host
  ansible.builtin.include_tasks:
    file: ../../tls/tasks/configure-cert.yml
  vars:
    cert_name: "{{ host.name }}"

- name: Install HTTPS Default Virtual Host
  ansible.builtin.template:
    src: vhost-default-https.conf
    dest: /etc/httpd/conf.d/vhosts.d/01-default.conf
    setype: httpd_config_t
    mode: '0644'
  notify:
    - Reload Apache

