- name: Install Zoneminder
  ansible.builtin.dnf:
    name:
      - zoneminder-common
      - zoneminder-httpd
      - php-fpm
    state: present

- name: Configure MySQL for Zoneminder
  ansible.builtin.include_tasks:
    file: ../../mysql/tasks/configure-db.yml

- name: Configure Apache for Zoneminder
  ansible.builtin.include_tasks:
    file: ../../http/tasks/configure-site.yml

- name: Install Zoneminder Configuration
  ansible.builtin.template:
    src: 03-custom.conf
    dest: "/etc/zm/conf.d/03-custom.conf"
    owner: root
    group: apache
    mode: '0640'
  notify:
    - Restart Zoneminder

- name: Enable/Start Zoneminder
  ansible.builtin.systemd_service:
    name: zoneminder.service
    enabled: true
    masked: no
    state: started

- name: Configure PHP Timezone
  ansible.builtin.lineinfile:
    path: /etc/php.ini
    regexp: '^date.timezone = '
    insertafter: '^;date.timezone =$'
    line: 'date.timezone = Europe/London'
    state: present

# TODO: File upstream bug about this
- name: Configure SELinux Context for Web Cache Directory
  ansible.builtin.file:
    path: /var/cache/zoneminder
    setype: httpd_cache_t
    state: directory

- name: Enable/Start PHP FPM
  ansible.builtin.systemd_service:
    name: php-fpm.service
    enabled: true
    masked: no
    state: started
