- name: Install Zoneminder
  ansible.builtin.dnf:
    name:
      - zoneminder-common
      - zoneminder-httpd
    state: present

- name: Configure MySQL for Zoneminder
  ansible.builtin.include_tasks:
    file: ../../mysql/tasks/configure-db.yml

- name: Install Zoneminder Configuration
  ansible.builtin.template:
    src: 03-custom.conf
    dest: "/etc/zm/conf.d/03-custom.conf"
    owner: root
    group: apache
    mode: '0640'
  notify:
    - Restart Zoneminder

- name: Enable/Start Zoneminder
  ansible.builtin.systemd_service:
    name: zoneminder.service
    enabled: true
    masked: no
    state: started
