- name: Install LibVirt
  ansible.builtin.dnf:
    name:
      - libvirt-daemon-driver-interface
      - libvirt-daemon-driver-network
      - libvirt-daemon-driver-nodedev
      - libvirt-daemon-driver-nwfilter
      - libvirt-daemon-driver-qemu
      - libvirt-daemon-driver-secret
      - libvirt-daemon-driver-storage
      - libvirt-daemon-lock
      - libvirt-daemon-log
      - libvirt-daemon-plugin-lockd
      - libvirt-daemon-proxy
      - python3-libvirt
      - python3-lxml
    state: present

- name: Enable/Start LibVirt Sockets
  ansible.builtin.systemd_service:
    name: "{{ item }}.socket"
    enabled: true
    masked: no
    state: started
  loop:
    - virtinterfaced
    - virtnetworkd
    - virtnodedevd
    - virtstoraged
    - virtsecretd
    - virtqemud
    - virtproxyd
