- name: Install LibVirt
  ansible.builtin.dnf:
    name:
      - libvirt
    state: present

# We don't use these hypervisors
- name: Disable LibVirt Support for VirtualBox and Xen
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: false
    masked: no
    state: stopped
  loop:
    - virtvboxd.service
    - virtvboxd-admin.socket
    - virtvboxd-ro.socket
    - virtvboxd.socket
    - virtxend.service
    - virtxend-admin.socket
    - virtxend-ro.socket
    - virtxend.socket

# Need to start all these sockets that otherwise would not be started until
# the next reboot
- name: Enable/Start LibVirt Sockets
  ansible.builtin.systemd_service:
    name: "{{ item }}.socket"
    enabled: true
    masked: no
    state: started
  loop:
    - virtinterfaced-admin
    - virtinterfaced-ro
    - virtinterfaced
    - virtlockd-admin
    - virtlockd
    - virtlogd-admin
    - virtlogd
    - virtlxcd-admin
    - virtlxcd-ro
    - virtlxcd
    - virtnetworkd-admin
    - virtnetworkd-ro
    - virtnetworkd
    - virtnodedevd-admin
    - virtnodedevd-ro
    - virtnodedevd
    - virtnwfilterd-admin
    - virtnwfilterd-ro
    - virtnwfilterd
    - virtproxyd-admin
    - virtproxyd-ro
    - virtproxyd
    - virtqemud-admin
    - virtqemud-ro
    - virtqemud
    - virtsecretd-admin
    - virtsecretd-ro
    - virtsecretd
    - virtstoraged-admin
    - virtstoraged-ro
    - virtstoraged
