# When including these tasks into a role, the following variables are
# available:
#
# - cert_name: subject of the certificate

# Provisions real certs via ACME challenge
- name: TLS - Configure Site Real TLS Certificate
  ansible.builtin.include_tasks:
    file: ../../tls/tasks/real-cert.yml
  when: not self_signed_certs
  vars:
    _cert_name: "{{ cert_name }}"

# Provisions self-signed certs via local CA
- name: TLS - Configure Site Self-Signed TLS Certificate
  ansible.builtin.include_tasks:
    file: ../../tls/tasks/self-cert.yml
  when: self_signed_certs
  vars:
    _cert_name: "{{ cert_name }}"
