# When including these tasks into a role, the following variables are
# available:
#
# - cert_name: set to override the default value of "role_name"

- name: Ensure Site TLS Certificate Directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: '0710'
  loop:
    - "/etc/letsencrypt/archive/{{ cert_name | default(role_name) }}"
    - "/etc/letsencrypt/live/{{ cert_name | default(role_name) }}"

# This section installs a pre-generated self-signed certificate if Certbot
# has not yet requested one from LetsEncrypt

- name: Checking For Installed TLS Certificates
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ cert_name | default(role_name) }}/fullchain.pem"
  register: tls_cert

- name: Installing Self-Signed TLS Certificates
  ansible.builtin.copy:
    src: "../../tls/files/{{ item }}"
    dest: "/etc/letsencrypt/live/{{ cert_name | default(role_name) }}/{{ item }}"
    owner: root
    group: root
    mode: '0640'
  loop:
    - fullchain.pem
    - cert.pem
    - chain.pem
    - privkey.pem
  when: not tls_cert.stat.exists
