- name: Install Certbot
  ansible.builtin.dnf:
    name:
      - certbot
    state: present

- name: Register Certbot ACME Account
  ansible.builtin.shell: |
    certbot -n register --agree-tos --no-eff-email --email webmaster@{{ domain }}
    touch /etc/letsencrypt/.registered
  args:
    creates: /etc/letsencrypt/.registered

- name: Enable/Start Certbot TLS Certificate Renewal Timer
  ansible.builtin.systemd_service:
    name: certbot-renew.timer
    enabled: true
    masked: no
    state: started
