- name: Install Cockpit
  ansible.builtin.dnf:
    name:
      - cockpit
      - cockpit-machines
      - cockpit-packagekit
      - cockpit-podman
      - cockpit-selinux
      - cockpit-storaged
    state: present

- name: Remove Cockpit NetworkManager Plugin
  ansible.builtin.dnf:
    name:
      - cockpit-networkmanager
    state: absent

- name: Configure Apache for Cockpit
  ansible.builtin.include_tasks:
    file: ../../http/tasks/configure-site.yml
  vars:
    site_proxy: true
    http_port: "{{ cockpit_http_port }}"

- name: Remove Cockpit Banner
  ansible.builtin.file:
    path: /etc/issue.d/cockpit.issue
    state: absent

- name: Install Cockpit Configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: cockpit.conf , dest: "/etc/cockpit/cockpit.conf" }
    - { src: disallowed-users , dest: "/etc/cockpit/disallowed-users" }
  notify:
    - Restart Cockpit

- name: Ensure Cockpit Socket Overrides Directory
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/cockpit.socket.d
    mode: '0755'

- name: Install Cockpit Socket Overrides
  ansible.builtin.template:
    src: cockpit.override.conf
    dest: "/etc/systemd/system/cockpit.socket.d/override.conf"
    mode: '0644'
  notify:
    - Restart Cockpit Socket

- name: Close Firewall for Direct Access to Cockpit
  ansible.posix.firewalld:
    service: cockpit
    permanent: true
    immediate: true
    state: disabled

- name: Enable/Start Cockpit Socket
  ansible.builtin.systemd_service:
    name: cockpit.socket
    enabled: true
    masked: no
    state: started
