- name: Configure Nginx for Cockpit
  ansible.builtin.include_tasks:
    file: ../../proxy/tasks/configure-site.yml

- name: Install Cockpit
  ansible.builtin.dnf:
    name:
      - cockpit
      - cockpit-machines
      - cockpit-pcp
      - cockpit-podman
      - cockpit-selinux
    state: present

- name: Install Cockpit Configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: cockpit-ws
    group: cockpit-ws
    mode: '0600'
  with_items:
    - { src: cockpit.conf.j2 , dest: "/etc/cockpit/cockpit.conf" }
    - { src: disallowed-users.j2 , dest: "/etc/cockpit/disallowed-users" }
  notify:
    - Restart Cockpit

- name: Enable/Start Cockpit
  ansible.builtin.systemd_service:
    name: cockpit.socket
    enabled: true
    masked: no
    state: started

- name: Enable/Start Perf Metric Logger
  ansible.builtin.systemd_service:
    name: pmlogger.service
    enabled: true
    masked: no
    state: started
