- name: Configure Apache for Cockpit
  ansible.builtin.include_tasks:
    file: ../../apache/tasks/configure-site.yml

- name: Install Cockpit
  ansible.builtin.dnf:
    name:
      - cockpit
      - cockpit-machines
      - cockpit-pcp
      - cockpit-podman
      - cockpit-selinux
    state: present

- name: Install Cockpit Configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: cockpit-ws
    group: cockpit-ws
    mode: '0600'
  loop:
    - { src: cockpit.conf , dest: "/etc/cockpit/cockpit.conf" }
    - { src: disallowed-users , dest: "/etc/cockpit/disallowed-users" }
  notify:
    - Restart Cockpit

- name: Ensure Cockpit Socket Overrides Directory
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/cockpit.socket.d
    mode: '0755'

- name: Install Cockpit Socket Overrides
  ansible.builtin.template:
    src: cockpit.override.conf
    dest: "/etc/systemd/system/cockpit.socket.d/override.conf"
    mode: '0644'
  notify:
    - Restart Cockpit Socket

- name: Close Firewall for Direct Access to Cockpit
  ansible.posix.firewalld:
    service: cockpit
    permanent: true
    state: disabled
  notify:
    - Reload Firewall

- name: Enable/Start Cockpit Socket
  ansible.builtin.systemd_service:
    name: cockpit.socket
    enabled: true
    masked: no
    state: started

- name: Enable/Start Perf Metric Logger
  ansible.builtin.systemd_service:
    name: pmlogger.service
    enabled: true
    masked: no
    state: started

# The default NAT device conflicts with the DHCP service, so we
# need to remove it, but for some reason it doesn't show up
# immediately, only after the Cockpit management interface is
# available so it's done here instead of in the virt role
- name: Delete Default LibVirt Network
  community.libvirt.virt_net:
    command: undefine
    name: default
