- name: Configure Apache for Cockpit
  ansible.builtin.include_tasks:
    file: ../../apache/tasks/configure-site.yml
  vars:
    site_proxy: true

- name: Install Cockpit
  ansible.builtin.dnf:
    name:
      - cockpit
      - cockpit-selinux
      - cockpit-packagekit
      - cockpit-storaged
      - cockpit-networkmanager
      - cockpit-389-ds
    state: present

# VM and container deps are separated out so they can be excluded from
# testing as they take a long time to install
- name: Install Cockpit Additional Features
  ansible.builtin.dnf:
    name:
      - cockpit-machines
      - cockpit-podman
    # No weak deps avoids virt-install -> libvirt-daemon-config-network
    # and this prevents the default virtual networking configuration
    # from clashing with our other DHCP and DNS services -- we'll be
    # creating virtual machines remotely using virt-manager anyway
    install_weak_deps: false
    state: present
  when: with_deps

- name: Install Cockpit Configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - { src: cockpit.conf , dest: "/etc/cockpit/cockpit.conf" }
    - { src: disallowed-users , dest: "/etc/cockpit/disallowed-users" }
  notify:
    - Restart Cockpit

- name: Ensure Cockpit Socket Overrides Directory
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/cockpit.socket.d
    mode: '0755'

- name: Install Cockpit Socket Overrides
  ansible.builtin.template:
    src: cockpit.override.conf
    dest: "/etc/systemd/system/cockpit.socket.d/override.conf"
    mode: '0644'
  notify:
    - Restart Cockpit Socket

- name: Close Firewall for Direct Access to Cockpit
  ansible.posix.firewalld:
    service: cockpit
    permanent: true
    state: disabled
  notify:
    - Reload Firewall

- name: Enable/Start Cockpit Socket
  ansible.builtin.systemd_service:
    name: cockpit.socket
    enabled: true
    masked: no
    state: started
