---
- hosts: all

  roles:
    - role: initial_setup
      tags: [ initial ]
    - role: cockpit
      vars:
        http_port: 9000
    - role: pihole
      vars:
        http_port: 9001
    - role: jenkins
      vars:
        http_port: 9002
    - role: home

  become: yes
  become_user: root
  become_method: sudo

  vars:
    domain: "matbooth.co.uk"
    host_name: "{{ inventory_hostname_short }}"
    host_fqdn: "{{ host_name }}.{{ domain }}"
    srv_name: "{{ role_name }}"
    srv_fqdn: "{{ srv_name }}.{{ domain }}"
    www_root: "/srv/www/{{ role_name }}"
