---
- hosts: all

  roles:
    - role: bootstrap
      tags: [ bootstrap ]
    - role: dns
    - role: dhcp
    - role: spotify
#    - role: sssd
#    - role: idp
#    - role: cockpit
#      vars:
#        http_port: 9090
#        with_deps: False
#    - role: ci
#      vars:
#        http_port: 9091
#    - role: openhab
#      vars:
#        http_port: 9092
    - role: photos
      vars:
        http_port: 9093
#    - role: home
  become: yes

  vars:
    domain: "{{ '.'.join(inventory_hostname.split('.')[1:]) }}"
    host:
      name: "{{ inventory_hostname_short }}"
      fqdn: "{{ inventory_hostname_short }}.{{ domain }}"
      ipv4:
        cidr:    "{{ inventory_host4 }}"
        address: "{{ inventory_host4 | ansible.utils.ipaddr('address') }}"
        subnet:  "{{ inventory_host4 | ansible.utils.ipsubnet }}"
        network: "{{ inventory_host4 | ansible.utils.ipaddr('network') }}"
        gateway: "{{ inventory_host4 | ansible.utils.ipsubnet | ansible.utils.ipaddr('1') | ansible.utils.ipaddr('address') }}"
      ipv6:
        cidr:    "{{ inventory_host6 }}"
        address: "{{ inventory_host6 | ansible.utils.ipaddr('address') }}"
        subnet:  "{{ inventory_host6 | ansible.utils.ipsubnet }}"
        network: "{{ inventory_host6 | ansible.utils.ipaddr('network') }}"
        gateway: "{{ inventory_host6 | ansible.utils.ipsubnet | ansible.utils.ipaddr('1') | ansible.utils.ipaddr('address') }}"
