## {{ ansible_managed }}

# Restrict this vhost to connections from the local network only
<Location />
	Require ip {{ host.ipv4.network }}/{{ host.ipv4.cidr | ansible.utils.ipaddr('prefix') }}
	Require ip {{ host.ipv6.network }}/{{ host.ipv6.cidr | ansible.utils.ipaddr('prefix') }}
	Require all denied
</Location>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
