- name: Enable OpenHAB Repository
  ansible.builtin.copy:
    src: openhab.repo
    dest: /etc/yum.repos.d/openhab.repo
    mode: '0644'

- name: Install OpenHAB
  ansible.builtin.dnf:
    name:
      - java-21-openjdk-headless
      - openhab
    state: present

- name: Configure Apache for OpenHAB
  ansible.builtin.include_tasks:
    file: ../../http/tasks/configure-site.yml
  vars:
    site_proxy: true
    http_port: "{{ openhab_http_port }}"

- name: Configure Public Key Authentication for OpenHAB Console
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/var/lib/openhab/etc/{{ item }}"
    mode: '0644'
  loop:
    - keys.properties
    - users.properties
  notify:
    - Restart OpenHAB

- name: Generate SSH Host Key Pair for OpenHAB Console
  community.crypto.openssh_keypair:
    path: /etc/openhab/ssh_host_rsa_key
    type: rsa
    size: 4096
    group: openhab
    owner: openhab
  notify:
    - Restart OpenHAB

- name: Open Firewall for OpenHAB Console
  ansible.posix.firewalld:
    port: "{{ openhab_ssh_port }}/tcp"
    permanent: true
    immediate: true
    state: enabled

- name: Install OpenHAB Configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - {src: openhab.env, dest: /etc/default/openhab }
    - {src: runtime.cfg, dest: /etc/openhab/services/runtime.cfg }
  notify:
    - Restart OpenHAB

- name: Enable/Start OpenHAB
  ansible.builtin.systemd_service:
    name: openhab.service
    enabled: true
    masked: no
    state: started

# OpenHAB can take a minute to come up and we need the console to be available
# for the next steps
- name: Wait On OpenHAB Start
  ansible.builtin.wait_for:
    host: "::1"
    port: "{{ openhab_ssh_port }}"

- name: Install OpenHAB Add-ons
  local_action: ansible.builtin.command ssh -p {{ openhab_ssh_port }} -i id_openhab openhab@{{ role_name }}.{{ domain }} openhab:addons install {{ item }}
  become: no
  register: openhab_addon_installation
  changed_when: openhab_addon_installation.stdout != "Add-on " + item + " is already installed."
  loop:
    - persistence-inmemory
    - persistence-mapdb
    - persistence-rrd4j
    - binding-astro
    - automation-jsscripting
