- name: Import GPG Key for OpenHAB Repository
  ansible.builtin.rpm_key:
    key: https://openhab.jfrog.io/artifactory/api/gpg/key/public
    state: present

- name: Enable OpenHAB Repository
  ansible.builtin.copy:
    src: openhab.repo
    dest: /etc/yum.repos.d/openhab.repo
    mode: '0644'

- name: Install OpenHAB
  ansible.builtin.dnf:
    name:
      - java-21-openjdk-headless
      - openhab
    state: present

- name: Configure Apache for OpenHAB
  ansible.builtin.include_tasks:
    file: ../../http/tasks/configure-site.yml
  vars:
    site_proxy: true

- name: Configure OpenHAB Embedded SSH Server
  ansible.builtin.lineinfile:
    path: "/var/lib/openhab/etc/org.apache.karaf.shell.cfg"
    regexp: "{{ item.re }}"
    line: "{{ item.line }}"
  loop:
    - { re: "^sshPort", line: "sshPort = 2222" }
    - { re: "^sshHost", line: "sshHost = ::1" }
  notify:
    - Restart OpenHAB

- name: Configure OpenHAB Embedded SSH Keys
  ansible.builtin.lineinfile:
    path: "/var/lib/openhab/etc/keys.properties"
    regexp: '(^\#karaf=)(.*)$'
    line: "openhab={{ (lookup('file', '~/.ssh/id_openhab.pub') | split(' '))[1] }},_g_:admingroup"
  notify:
    - Restart OpenHAB

- name: Ensure OpenHAB Service Overrides Directory
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/openhab.service.d
    mode: '0755'

- name: Install OpenHAB Service Overrides
  ansible.builtin.template:
    src: openhab.override.conf
    dest: "/etc/systemd/system/openhab.service.d/override.conf"
    mode: '0644'
  notify:
    - Restart OpenHAB

- name: Enable/Start OpenHAB
  ansible.builtin.systemd_service:
    name: openhab.service
    enabled: true
    masked: no
    state: started

