- name: Install LDAP
  ansible.builtin.dnf:
    name:
      - 389-ds-base
    state: present

- name: Configure DNS CNAME For LDAP
  ansible.builtin.include_tasks:
    file: ../../dns/tasks/configure-record.yml

- name: Configure DNS SRV Record for LDAP
  ansible.builtin.include_tasks:
    file: ../../dns/tasks/configure-record.yml
  vars:
    record_name: "_ldap._tcp"
    record_type: "SRV"
    text: "0 100 389 {{ role_name }}.{{ domain }}"

- name: Install LDAP Instance Creation Template
  ansible.builtin.template:
    src: instance.inf
    dest: /etc/dirsrv/instance.inf
    mode: '0600'

- name: Create LDAP Instance
  ansible.builtin.command:
    cmd: "dscreate from-file /etc/dirsrv/instance.inf"
    creates: "/etc/dirsrv/slapd-{{ ldap_instance }}/dse.ldif"
  register: slapd_instance

- name: Enable/Start LDAP
  ansible.builtin.systemd_service:
    name: "dirsrv@{{ ldap_instance }}.service"
    enabled: true
    masked: no
    state: started

- name: Enable LDAP MemberOf Plugin
  ansible.builtin.command:
    cmd: "{{ item }}"
  loop:
    - "dsconf accounts plugin memberof enable"
    - "dsconf accounts plugin memberof set --scope {{ ldap_domain }}"
    - "dsctl accounts restart"
  when: slapd_instance.changed

- name: Configure LDAP TLS Certificate
  ansible.builtin.include_tasks:
    file: ../../tls/tasks/configure-cert.yml
  vars:
    cert_name: "{{ role_name }}"

- name: Import LDAP Server TLS Certificates
  ansible.builtin.command:
    cmd: "{{ item }}"
  loop:
    - "dsconf accounts security ca-certificate add --file /etc/letsencrypt/certs/{{ role_name }}.{{ domain }}/chain.pem --name 'Server-CA'"
    - "dsctl accounts tls import-server-key-cert /etc/letsencrypt/certs/{{ role_name }}.{{ domain }}/cert.pem /etc/letsencrypt/certs/{{ role_name }}.{{ domain }}/privkey.pem"
    - "dsconf accounts security certificate add --file /etc/letsencrypt/certs/{{ role_name }}.{{ domain }}/cert.pem --primary-cert --name 'Server-Cert'"
    - "dsconf accounts config replace nsslapd-security=on"
    - "dsconf accounts config replace nsslapd-listenhost={{ role_name }}.{{ domain }}"
    - "dsconf accounts config replace nsslapd-securelistenhost={{ role_name }}.{{ domain }}"
    - "dsctl accounts restart"
  when: slapd_instance.changed

- name: Determine Initial LDAP User Details
  local_action: ansible.builtin.command getent passwd {{ lookup('env', 'USER') }}
  register: ldap_initial_user
  changed_when: False

- name: Create Facts About Initial LDAP User
  ansible.builtin.set_fact:
    ldap_initial_user_id: "{{ (ldap_initial_user.stdout | split(':'))[0] }}"
    ldap_initial_user_uid: "{{ (ldap_initial_user.stdout | split(':'))[2] }}"
    ldap_initial_user_gid: "{{ (ldap_initial_user.stdout | split(':'))[3] }}"
    ldap_initial_user_gecos: "{{ (ldap_initial_user.stdout | split(':'))[4] }}"

- name: Create Initial LDAP User
  ansible.builtin.command:
    cmd: "dsidm -v -b {{ ldap_domain }} {{ ldap_instance }} {{ item }}"
  loop:
    - "organizationalunit create --ou People"
    - "organizationalunit create --ou Groups"
    - "organizationalunit create --ou Services"
    - "posixgroup create --cn wheel --gidNumber 10"
    - "posixgroup create --cn users --gidNumber 100"
    - "posixgroup create --cn {{ ldap_initial_user_id }} --gidNumber {{ ldap_initial_user_gid }}"
    - "user create --cn {{ ldap_initial_user_id }} --uid {{ ldap_initial_user_id }} --uidNumber {{ ldap_initial_user_uid }} --gidNumber {{ ldap_initial_user_gid }} --displayName '{{ ldap_initial_user_gecos }}' --homeDirectory /home/{{ ldap_initial_user_id }}"
    - "group add_member wheel uid={{ ldap_initial_user_id }},ou=People,{{ ldap_domain }}"
    - "group add_member users uid={{ ldap_initial_user_id }},ou=People,{{ ldap_domain }}"
    - "group add_member {{ ldap_initial_user_id }} uid={{ ldap_initial_user_id }},ou=People,{{ ldap_domain }}"
  when: slapd_instance.changed

- name: Install LDAP Service Environment Configuration
  ansible.builtin.template:
    src: "dirsrv"
    dest: "/etc/sysconfig/dirsrv"
  notify:
    - Restart LDAP

- name: Install TLS Certificate Renewal Hook for LDAP Service
  ansible.builtin.template:
    src: dirsrv_cert_hook.sh
    dest: "/etc/letsencrypt/renewal-hooks/post/dirsrv_cert_hook.sh"
    mode: '755'

- name: Install LDAP Client Configuration
  ansible.builtin.template:
    src: ldap.conf
    dest: /etc/openldap/ldap.conf
    mode: '0644'

- name: Open Firewall for LDAP
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - ldap
    - ldaps
  notify:
    - Reload Firewall
