## {{ ansible_managed }}

#
# This file contains the valid users who can log into Karaf. Each line have to be of
# the format:
#
# USER=KEY,ROLE1,ROLE2,...
#
# All users and roles entered in this file are available after Karaf startup
# and modifiable via the JAAS command group. These users reside in a JAAS domain
# with the name "karaf"..
#
openhab={{ (lookup('file', '~/.ssh/id_openhab.pub') | split(' '))[1] }},_g_:admingroup
_g_\:admingroup = group,admin,manager,viewer,systembundles,ssh
