- name: Ensure Site Directories
  ansible.builtin.file:
    state: directory
    path: "{{ item.path }}"
    group: "{{ item.group }}"
    owner: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: '/var/log/nginx/{{ role_name }}', group: 'root', owner: 'root', mode: '0711' }
    - { path: '/etc/nginx/includes.d/{{ role_name }}', group: 'root', owner: 'root', mode: '0755' }

# This section adds a DNS alias so that the site is addressable and the
# name-based vhosts function properly

- name: Add CNAME Record to the DNS Zone
  ansible.builtin.lineinfile:
    path: "/srv/db/dns/{{ domain }}.zone"
    regexp: "^{{ role_name }}"
    line: "{{ role_name }}\tIN\tCNAME\t{{ host.fqdn }}."
  register: cname_zone
  notify:
    - Reload BIND DNS

- name: Bump the Timestamp in the SOA DNS Record
  ansible.builtin.lineinfile:
    path: "/srv/db/dns/{{ domain }}.zone"
    regexp: "(.*)SOA(.*)[0-9]{10,10}(.*)"
    line: "\\1SOA\\g<2>{{ now(utc=true,fmt='%y%m%d%H%M') }}\\3"
    backrefs: true
  when: cname_zone.changed

# This section installs a pre-generated self-signed certificate if Certbot
# has not yet requested one from LetsEncrypt

- name: Ensure Site TLS Certificate Directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: '0710'
  with_items:
    - "/etc/letsencrypt/archive/{{ srv_fqdn }}"
    - "/etc/letsencrypt/live/{{ srv_fqdn }}"

- name: Checking For Installed TLS Certificate
  stat:
    path: "/etc/letsencrypt/live/{{ srv_fqdn }}/fullchain.pem"
  register: tls_cert

- name: Installing Self-Signed TLS Certificate
  copy:
    src: "../../proxy/files/cert.pem"
    dest: "/etc/letsencrypt/live/{{ srv_fqdn }}/fullchain.pem"
    owner: root
    group: root
    mode: '0640'
  when:
    - not tls_cert.stat.exists

- name: Checking For Installed TLS Certificate Key
  stat:
    path: "/etc/letsencrypt/live/{{ srv_fqdn }}/privkey.pem"
  register: tls_key

- name: Installing Self-Signed TLS Certificate Key
  copy:
    src: "../../proxy/files/key.pem"
    dest: "/etc/letsencrypt/live/{{ srv_fqdn }}/privkey.pem"
    owner: root
    group: root
    mode: '0640'
  when:
    - not tls_key.stat.exists

# This file configures a vhost for the calling role, including all necessary TLS
# moving parts

- name: Install Site Virtual Host
  ansible.builtin.template:
    src: ../../proxy/templates/nginx.vhost.conf
    dest: "/etc/nginx/vhosts.d/{{ role_name }}.conf"
    mode: '0644'
  notify:
    - Reload Nginx

# All files supplied by the calling role named like "*.nginx.conf" will be
# included by the above vhost configuration

- name: Install Site Custom Config
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/nginx/includes.d/{{ role_name }}/{{ item | basename | regex_replace('\\.nginx\\.conf$', '.conf') }}"
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - "{{ role_path }}/templates/*.nginx.conf"
  notify:
    - Reload Nginx
