- name: Install Nginx And Certbot
  ansible.builtin.dnf:
    name:
      - nginx
      - certbot
    state: present

- name: Create Nginx Directories
  ansible.builtin.file:
    state: directory
    setype: "{{ item.setype }}"
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: /etc/nginx/vhosts.d, setype: httpd_config_t, mode: '0755' }
    - { path: /etc/nginx/includes.d, setype: httpd_config_t, mode: '0755' }
    - { path: "{{ www_root | dirname }}", setype: httpd_sys_content_t, mode: '0755' }

- name: Configure SELinux To Allow Nginx Proxy Connections
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: Install Nginx Main Configuration
  ansible.builtin.template:
    src: nginx.conf
    dest: "/etc/nginx/nginx.conf"
    group: root
    owner: root
    mode: '0644'
  notify:
    - Reload Nginx

- name: Enable/Start Nginx
  ansible.builtin.systemd_service:
    name: nginx.service
    enabled: true
    masked: no
    state: started

- name: Enable/Start Nginx TLS Certificate Renewal Timer
  ansible.builtin.systemd_service:
    name: certbot-renew.timer
    enabled: true
    masked: no
    state: started

- name: Open Firewall for HTTP/HTTPS
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - http
    - https
  notify:
    - Reload Firewall
