- name: Enable Immich Repository
  community.general.copr:
    state: enabled
    name: mbooth/immich

# Install latest version always because we are building this RPM
# ourselves
- name: Install Immich And Postgresql Extensions
  ansible.builtin.dnf:
    name:
      - immich
      - python3-immich_ml
      - python3-immich_ml+cpu
      - VectorChord
    state: latest

# Check if extension is configured correctly first to avoid unnecessary restart
# of PostgreSQL -- reports changed if the required config is absent
- name: Check PostgreSQL Extension Configuration
  ansible.builtin.command:
    cmd: "grep '^shared_preload_libraries.*vchord.*$' /var/lib/pgsql/data/postgresql.auto.conf"
  register: preload_lib_config
  changed_when: preload_lib_config.rc != 0
  failed_when: False

# This extension must be loaded at PostgreSQL start up time
- name: Configure VectorChord Extension for PostgreSQL
  community.postgresql.postgresql_set:
    name: shared_preload_libraries
    value: vchord,vector
  when: preload_lib_config.changed
  register: preload_lib

# A change to shared_preload_libraries requires PostgreSQL to be restarted
# immediately before we may use the extension
- name: Restart PostgreSQL
  ansible.builtin.systemd_service:
    name: postgresql.service
    state: restarted
  when: preload_lib.changed

- name: Configure PostgreSQL for Immich
  ansible.builtin.include_tasks:
    file: ../../postgres/tasks/configure-db.yml
  vars:
    db_extensions:
    - vchord
    - earthdistance

- name: Configure Apache for Immich
  ansible.builtin.include_tasks:
    file: ../../http/tasks/configure-site.yml
  vars:
    site_proxy: true
    http_port: "{{ immich_http_port }}"

- name: Configure Keycloak for Immich
  ansible.builtin.include_tasks:
    file: ../../id/tasks/configure-client.yml
  vars:
    client:
      name: "Immich"
      description: "Photo and Video Management"
      secret: "{{ immich_secret }}"
      redirect_uris: [ "app.immich:///oauth-callback", "/auth/login", "/user-settings" ]

- name: Install Immich Configuration
  ansible.builtin.template:
    src: immich.env
    dest: "/etc/sysconfig/immich"
    mode: '0644'
  notify:
    - Restart Immich

- name: Enable/Start Immich
  ansible.builtin.systemd_service:
    name: "{{ item }}.service"
    enabled: true
    masked: no
    state: started
  loop:
    - immich-machine-learning
    - immich

