## {{ ansible_managed }}

# For all configuration options, see:
# - https://www.keycloak.org/server/all-config

# Database

db=postgres
db-username={{ db_user }}
db-password={{ db_password }}
db-url-database={{ db_name }}
db-url-host=::1
db-url-port=5432

# HTTP

http-enabled=true
http-port={{ kc_http_port }}
http-host=::1

# Hostname

hostname={{ role_name }}.{{ domain }}

# Proxy

proxy-headers=xforwarded
