# Dynamic Zone Update Keys
include "/etc/named/dhcp-ddns.key";

zone "{{ domain }}" IN {
	type master;
	file "{{ data_dir }}/{{ domain }}.zone";
	update-policy {
		grant dhcp-ddns wildcard *.{{ domain }} A AAAA DHCID;
	};
};

zone "{{ host.cidr4 | ip_ptr }}" IN {
	type master;
	file "{{ data_dir }}/{{ host.cidr4 | ip_ptr }}.zone";
	update-policy {
		grant dhcp-ddns wildcard *.{{ host.cidr4 | ip_ptr }} PTR DHCID;
	};
};

zone "{{ host.cidr6 | ip_ptr }}" IN {
	type master;
	file "{{ data_dir }}/{{ host.cidr6 | ip_ptr }}.zone";
	update-policy {
		grant dhcp-ddns wildcard *.{{ host.cidr6 | ip_ptr }} PTR DHCID;
	};
};

