# Dynamic Zone Update Keys
include "/etc/named/dhcp-ddns.key";

zone "{{ domain }}" IN {
	type master;
	file "{{ data_dir }}/{{ domain }}.zone";
	update-policy {
		grant dhcp-ddns wildcard *.{{ domain }} A AAAA CNAME DHCID;
	};
};

zone "{{ host.ipv4.bond | ip_ptr }}" IN {
	type master;
	file "{{ data_dir }}/{{ host.ipv4.bond | ip_ptr }}.zone";
	update-policy {
		grant dhcp-ddns wildcard *.{{ host.ipv4.bond | ip_ptr }} PTR DHCID;
	};
};

zone "{{ host.ipv6.bond | ip_ptr }}" IN {
	type master;
	file "{{ data_dir }}/{{ host.ipv6.bond | ip_ptr }}.zone";
	update-policy {
		grant dhcp-ddns wildcard *.{{ host.ipv6.bond | ip_ptr }} PTR DHCID;
	};
};

