zone "{{ domain }}" IN {
        type master;
        file "{{ data_dir }}/{{ domain }}.zone";
        allow-update { none; };
};

zone "{{ host.cidr4 | ip_ptr }}" IN {
        type master;
        file "{{ data_dir }}/{{ host.cidr4 | ip_ptr }}.zone";
        allow-update { none; };
};

zone "{{ host.cidr6 | ip_ptr }}" IN {
        type master;
        file "{{ data_dir }}/{{ host.cidr6 | ip_ptr }}.zone";
        allow-update { none; };
};

