acl internal-network {
	{{ host.ipv4.subnet }};
	{{ host.ipv6.subnet }};
};

options {
	listen-on port {{ bind9_port }} {
		{{ host.ipv4.address }};
	};
	listen-on-v6 port {{ bind9_port }} {
		{{ host.ipv6.address }};
	};
	directory 	"/var/named";
	dump-file 	"/var/named/data/cache_dump.db";
	statistics-file "/var/named/data/named_stats.txt";
	memstatistics-file "/var/named/data/named_mem_stats.txt";
	secroots-file	"/var/named/data/named.secroots";
	recursing-file	"/var/named/data/named.recursing";
	allow-query     { localhost; internal-network; };
	allow-recursion { localhost; internal-network; };
	allow-transfer  { localhost; };

	recursion yes;

	dnssec-validation auto;

	managed-keys-directory "/var/named/dynamic";
	geoip-directory "/usr/share/GeoIP";

	pid-file "/run/named/named.pid";
	session-keyfile "/run/named/session.key";

	/* https://fedoraproject.org/wiki/Changes/CryptoPolicy */
	include "/etc/crypto-policies/back-ends/bind.config";
};

logging {
        channel default_debug {
                syslog daemon;
                severity dynamic;
        };
};

# Root Zones
zone "." IN {
	type hint;
	file "named.ca";
};

# Localhost Zones
include "/etc/named.rfc1912.zones";

# Root Keys
include "/etc/named.root.key";

# Hosted Domains
include "/etc/named/domains.conf";

