## {{ ansible_managed }}

# Override the default nameserver configuration for this network

[Match]
Name=bridge0

[Network]
DNS=
DNS={{ host.ipv4.address }}
DNS={{ host.ipv6.address }}
Domains={{ domain }}
