[Unit]
# It's possible for this service to be up before the database is up,
# so we specify a hard requirement here to avoid DHCP failure
Requires=postgresql.service
After=postgresql.service
# Avoid trying to bind to the virtual interface before it is available
After=sys-devices-virtual-net-bond0.device
