// This configuration file contains only DHCPv4 server's configuration.
// If configurations for other Kea services are also included in this file they
// are ignored by the DHCPv4 server.
{

"Dhcp4": {
    "interfaces-config": {
        "interfaces": [ "bond0" ]

        // Kea DHCPv4 server by default listens using raw sockets. This ensures
        // all packets, including those sent by directly connected clients
        // that don't have IPv4 address yet, are received. However, if your
        // traffic is always relayed, it is often better to use regular
        // UDP sockets. If you want to do that, uncomment this line:
        // "dhcp-socket-type": "udp"
    },

    "control-socket": {
        "socket-type": "unix",
        "socket-name": "/tmp/kea4-ctrl-socket"
    },

    "lease-database": {
        "type": "postgresql",
        "name": "{{ db_name }}",
        "user": "{{ db_user }}",
        "password": "{{ db_password }}",
        "host": "::1",
        "port": 5432
    },

    "hosts-database": {
        "type": "postgresql",
        "name": "{{ db_name }}",
        "user": "{{ db_user }}",
        "password": "{{ db_password }}",
        "host": "::1",
        "port": 5432
    },

    // Set long lease lifetimes and infrequent timers, our network is not
    // very dynamic and we don't need to be aggressive
    "renew-timer": 21600,
    "rebind-timer": 32400,
    "valid-lifetime": 43200,
    "expired-leases-processing": {
        "reclaim-timer-wait-time": 3600,
        "flush-reclaimed-timer-wait-time": 7200,
        "hold-reclaimed-time": 172800,
        "max-reclaim-leases": 0,
        "max-reclaim-time": 0,
        "unwarned-reclaim-cycles": 5
    },

    "subnet4": [
        {
            "id": 1,
            "subnet": "192.168.122.0/24",
            "pools": [
                { "pool": "192.168.122.100 - 192.168.122.199" }
            ],
            "option-data": [
                {
                    // Gateways
                    "name": "routers",
                    "data": "{{ host_gw }}"
                },
                {
                    // Name servers
                    "name": "domain-name-servers",
                    "data": "{{ host_dns }}"
                }
            ],
            "reservations": [
            ]
        }
    ],

    // DDNS information (how the DHCPv4 component can reach a DDNS daemon)
    "dhcp-ddns": {
        "enable-updates": true,
        "server-ip": "::1",
        "server-port": 53001,
        "sender-ip": "::1",
        "sender-port": 0,
        "max-queue-size": 1024
    },
    "ddns-send-updates": false,

    "loggers": [
        {
            // This specifies the logging for DHCPv4 daemon.
            "name": "kea-dhcp4",
            "output_options": [
                {
                    // Logs written to stdout will be captured by systemd
                    "output": "stdout",

                    // Shorter log pattern suitable for use with systemd,
                    // avoids redundant information
                    "pattern": "%-5p [%c] %m\n"
                }
            ],
            // This specifies the severity of log messages to keep. Supported values
            // are: FATAL, ERROR, WARN, INFO, DEBUG
            "severity": "INFO",

            // If DEBUG level is specified, this value is used. 0 is least verbose,
            // 99 is most verbose. Be cautious, Kea can generate lots and lots
            // of logs if told to do so.
            "debuglevel": 0
        }
    ]
}
}
