- name: Install Avahi
  ansible.builtin.dnf:
    name:
      - avahi
    state: present

- name: Install Avahi Configuration
  ansible.builtin.template:
    src: avahi-daemon.conf
    dest: "/etc/avahi/avahi-daemon.conf"
    mode: '0644'
  notify:
    - Restart Avahi

- name: Enable/Start Avahi
  ansible.builtin.systemd_service:
    name: avahi-daemon.service
    enabled: true
    masked: no
    state: started

- name: Open Firewall for Avahi
  ansible.posix.firewalld:
    service: mdns
    permanent: true
    state: enabled
  notify:
    - Reload Firewall
