- name: Install Kerberos
  ansible.builtin.dnf:
    name:
      - krb5-server
      - krb5-workstation
    state: present

- name: Configure DNS Records for Kerberos Services
  ansible.builtin.include_tasks:
    file: ../../dns/tasks/configure-record.yml
  loop:
    - name: "{{ role_name }}.{{ domain }}"
      type: A
      text: "{{ host.ipv4.address }}"
    - name: "{{ role_name }}.{{ domain }}"
      type: AAAA
      text: "{{ host.ipv6.address }}"
    - name: "_kerberos._udp.{{ domain }}"
      type: SRV
      text: "0 100 88 {{ role_name }}.{{ domain }}."
    - name: "_kerberos._tcp.{{ domain }}"
      type: SRV
      text: "0 100 88 {{ role_name }}.{{ domain }}."
    - name: "_kpasswd._udp.{{ domain }}"
      type: SRV
      text: "0 100 464 {{ role_name }}.{{ domain }}."
    - name: "_kpasswd._tcp.{{ domain }}"
      type: SRV
      text: "0 100 464 {{ role_name }}.{{ domain }}."
    - name: "_kerberos.{{ domain }}"
      type: TXT
      text: "{{ krb_realm }}"
  loop_control:
    loop_var: record

- name: Install Kerberos Configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: krb5.conf, dest: /etc/krb5.conf, mode: '0644' }
    - { src: kdc.conf, dest: /var/kerberos/krb5kdc/kdc.conf, mode: '0600' }
    - { src: kadm5.acl, dest: /var/kerberos/krb5kdc/kadm5.acl, mode: '0600' }
  notify:
    - Restart KDC
    - Restart KAdmin

- name: Initialise Kerberos Principal Database
  ansible.builtin.command:
    cmd: "/usr/sbin/kdb5_util create -r {{ krb_realm }} -s -P {{ krb_master_password }}"
    creates: /var/kerberos/krb5kdc/principal
  no_log: true

- name: Enable/Start Kerberos
  ansible.builtin.systemd_service:
    name: "{{ item }}.service"
    enabled: true
    masked: no
    state: started
  loop:
    - krb5kdc
    - kadmin

- name: Create Kerberos Host Keytab
  ansible.builtin.include_tasks:
    file: configure-keytab.yml
  vars:
    keytab_principals: [ "host/{{ host.fqdn }}" ]
    keytab_path: /etc/krb5.keytab

- name: Open Firewall for Kerberos
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - kerberos
    - kpasswd
