- name: Configure Nginx for Homer Dashboard
  ansible.builtin.include_tasks:
    file: ../../proxy/tasks/configure-site.yml

- name: Download Homer Dashboard
  ansible.builtin.get_url:
    url: https://github.com/bastienwirtz/homer/releases/download/v23.10.1/homer.zip
    dest: /srv/homer-v23.10.1.zip

- name: Install Homer Dashboard
  ansible.builtin.unarchive:
    src: /srv/homer-v23.10.1.zip
    dest: "{{ www_root }}"
    remote_src: yes

