- name: Configure Apache for Homer Dashboard
  ansible.builtin.include_tasks:
    file: ../../apache/tasks/configure-site.yml
  vars:
    site_static: true

- name: Download Homer Dashboard
  ansible.builtin.get_url:
    url: "https://github.com/bastienwirtz/homer/releases/download/v{{ version }}/homer.zip"
    dest: "/srv/homer-v{{ version }}.zip"
  register: download

- name: Install Homer Dashboard
  ansible.builtin.unarchive:
    src: "/srv/homer-v{{ version }}.zip"
    dest: "{{ www_root }}/{{ role_name }}"
    remote_src: yes
  when: download.changed

- name: Ensure Homer Assets Directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    mode: '0755'
  loop:
    - { path: "{{ www_root }}/{{ role_name }}/assets/tools", state: absent }
    - { path: "{{ www_root }}/{{ role_name }}/assets/services", state: directory }

- name: Copy Homer Assets
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ www_root }}/{{ role_name }}/assets/services"
    mode: '0644'
  with_fileglob:
    - "*.png"
  notify:
    - Reload Apache

- name: Install Homer Configuration
  ansible.builtin.template:
    src: config.yml
    dest: "{{ www_root }}/{{ role_name }}/assets/config.yml"
    mode: '0644'
