# These tasks create a bonded ethernet connection from all the ports
# on the Intel NIC and creates a virtual bridge. The bonded connection
# and all virtual machines will be connected to the virtual bridge:
#
#               Server
#  Gateway     ┌─────────────────────────────────────────────┐
# ┌────────┐  ┌┴───────┐                                     │
# │ WAN    │<─│ enp2   │<───────────────┐                    │
# └────────┘  └┬───────┘                │                    │
#              │                        │                    │
#  Switch      │                        │         libvirt    │
# ┌────────┐  ┌┴───────┐  ┌───────┐     │        ┌────────┐  │
# │ Port 1 │─>│ enp4f0 │─>│       │  ┌───────┐  ┌┴──────┐ │  │
# │        │  └┬───────┘  │       │  │       │<─│ vnet0 │ │  │
# │        │  ┌┴───────┐  │       │  │       │  └┬──────┘ │  │
# │ Port 2 │─>│ enp4f1 │─>│       │  │       │  ┌┴──────┐ │  │
# │        │  └┬───────┘  │ bond0 │─>│bridge0│<─│ vnet1 │ │  │
# │        │  ┌┴───────┐  │       │  │       │  └┬──────┘ │  │
# │ Port 3 │─>│ enp4f2 │─>│       │  │       │  ┌┴──────┐ │  │
# │        │  └┬───────┘  │       │  │       │<─│ vnet2 │ │  │
# │        │  ┌┴───────┐  │       │  └───────┘  └┬──────┘ │  │
# │ Port 4 │─>│ enp4f3 │─>│       │              └────────┘  │
# │        │  └┬───────┘  └───────┘                          │
# │        │   └─────────────────────────────────────────────┘
# │ Port n │─> ...
# └────────┘

- name: Create Bonded Connection
  community.general.nmcli:
    type: bond
    conn_name: bond0
    autoconnect: true
    mode: balance-xor
    state: present
  register: bond_config
  when: "'bond0' not in ansible_facts"

- name: Add Wired NICs to Bonded Connection
  community.general.nmcli:
    type: ethernet
    slave_type: bond
    master: bond0
    ifname: "{{ item }}"
    conn_name: "{{ item }}"
    state: present
  loop: "{{ ether_interfaces[1:] }}"
  when: item.startswith('en')

- name: Reapply Bonded Connection Settings
  ansible.builtin.command:
    cmd: "nmcli device reapply bond0"
  when: bond_config.changed

- name: Create Virtual Network Bridge
  community.general.nmcli:
    type: bridge
    conn_name: bridge0
    autoconnect: true
    ip4: "{{ host.ipv4.cidr }}"
    gw4: "{{ host.ipv4.gateway }}"
    dns4: "127.0.0.1"
    dns4_search: "{{ domain }}"
    ip6: "{{ host.ipv6.cidr }}"
    gw6: "{{ host.ipv6.gateway }}"
    dns6: "::1"
    dns6_search: "{{ domain }}"
    stp: true
    state: present
  register: bridge_config
  when: "'bridge0' not in ansible_facts"

- name: Add Bonded Ethernet NIC as a Virtual Network Bridge Port
  community.general.nmcli:
    type: ethernet
    slave_type: bridge
    master: bridge0
    ifname: bond0
    conn_name: bond0
    state: present

- name: Reapply Virtual Network Bridge Settings
  ansible.builtin.command:
    cmd: "nmcli device reapply bridge0"
  when: bridge_config.changed
