# Role for configuring network connections, any subsequent role that
# refers directly to either the bond0 or bridge0 interfaces should
# express a dependency on this role

- name: Permanantly Disable Wifi Adapter
  ansible.builtin.command:
    cmd: /usr/sbin/rfkill block wlan
  changed_when: False

# This should find all physical interfaces no matter how they are
# named and return them in a predictable order
- name: Create List of Wired NICs
  ansible.builtin.set_fact:
    ether_interfaces: "{{ ansible_interfaces | sort | map('extract', ansible_facts) | selectattr('type', 'eq', 'ether') | map(attribute='device') }}"

- name: Configure Network Connections
  ansible.builtin.include_tasks:
    file: configure-network.yml

# Disable the systemd stub listener in favour of using the configured
# DNS resolvers directly
- name: Disable Local Resolver's Stub Listener
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: 'DNSStubListener=yes'
    line: 'DNSStubListener=no'

# Bit overkill, but I couldn't figure out how to bring up the bonded
# connection/virtual bridge without killing Ansible's SSH connection
- name: Reboot Machine
  ansible.builtin.reboot:
    msg: "Rebooting to switch to bonded network connection"
  when: "'bond0' not in ansible_facts or 'bridge0' not in ansible_facts"

# We may want to refer to the new interfaces later on, so regather the
# facts if necessary
- name: Regather Facts About the New Network Connections
  ansible.builtin.setup:
  when: "'bond0' not in ansible_facts or 'bridge0' not in ansible_facts"
