- name: Install Ipsilon
  ansible.builtin.dnf:
    name:
      - ipsilon
      - ipsilon-client
      - ipsilon-authgssapi
      - ipsilon-authpam
      - ipsilon-saml2
      - python3-mod_wsgi
      - mod_auth_gssapi
      - mod_auth_mellon
    state: present

- name: Configure Apache for Ipsilon Identity Provider
  ansible.builtin.include_tasks:
    file: ../../http/tasks/configure-site.yml

- name: Create Ipsilon Instance
  ansible.builtin.command:
    cmd: "/usr/sbin/ipsilon-server-install --gssapi=yes --gssapi-httpd-keytab=/etc/httpd/http.keytab --pam=yes --saml2=yes --root-instance --hostname {{ role_name }}.{{ domain }} --admin-user={{ ldap_initial_user_id }}"
    creates: /var/lib/ipsilon/root

- name: Install Ipsilon Instance Configuration
  ansible.builtin.template:
    src: ipsilon.conf
    dest: "/etc/ipsilon/root/ipsilon.conf"
    owner: ipsilon
    group: ipsilon
    mode: '0600'
  notify:
    - Reload Apache

- name: Ensure Apache SAML2 Metadata Directory
  ansible.builtin.file:
    state: directory
    path: "/etc/httpd/saml2"
    owner: apache
    group: apache
    mode: '0700'

- name: Install Apache SAML2 Metadata
  ansible.builtin.copy:
    src: "/var/lib/ipsilon/root/saml2/metadata.xml"
    dest: "/etc/httpd/saml2/idp-metadata.xml"
    owner: apache
    group: apache
    mode: '0600'
    remote_src: True
