- name: Install LibVirt
  ansible.builtin.dnf:
    name:
      - libvirt-daemon
      - qemu-kvm-core
    state: latest

- name: Enable/Start LibVirt
  ansible.builtin.systemd_service:
    name: libvirtd.service
    enabled: true
    masked: no
    state: started
