# When including these tasks into a role, the following variables
# must be defined:
#
#  - db_name
#  - db_user
#  - db_password

- name: MySQL - Create New Database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present
  register: db_creation

- name: MySQL - Create Database User
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    column_case_sensitive: false
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present

- name: MySQL - Initialise Database
  community.mysql.mysql_db:
    name: all
    target: "{{ db_import_script }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: import
  when: db_creation.changed
