## {{ ansible_managed }}

# The well known authentication provider URI for configuration self-discovery
OIDCProviderMetadataURL https://id.{{ domain }}/realms/{{ domain }}/.well-known/openid-configuration

# A virtual URI for mod_auth_oidc to use to trigger interactions with the authentication provider
# It must be inside the protected area, but not overlap with any URI the app uses to serve content
OIDCRedirectURI /protected/redirect_uri

# The app's credentials as a client of the authentication provider
OIDCClientID test_app
OIDCClientSecret {{ test_app_secret }}

OIDCCryptoPassphrase seekrit_passphrase
OIDCScope "openid email profile"
OIDCRemoteUserClaim preferred_username
OIDCPassClaimsAs environment

# Authorise access to various parts of the app, see:
# - https://github.com/OpenIDC/mod_auth_openidc/wiki/Authorization

# Authorise any user, anonymous or authenticated.
<Location />
	AuthType openid-connect
	Require valid-user
	OIDCUnAuthAction pass
</Location>

# Authorise authenticated users only.
<Location /protected>
	AuthType openid-connect
	Require valid-user
	OIDCUnAuthAction auth
</Location>

# Authorise users based on claims that have been provided for that user.
<Location /protected/admins_only>
	AuthType openid-connect
	# Assuming the "groups" claim is a list of groups the user is a member of:
	Require claim groups:test_app_admins
	OIDCUnAuthAction auth
</Location>

# Convenient virtual logout and login URIs for the app to use
RedirectTemp /logout /protected/redirect_uri?logout=https://{{ role_name }}.{{ domain }}/
<Location /login>
	AuthType openid-connect
	Require valid-user
	OIDCUnAuthAction auth
	# After authentication, user will be redirected to the URI passed in the query string
	RewriteEngine On
	RewriteCond %{QUERY_STRING} ^target=(.+)$
	RewriteRule (.*) %1? [R=302,L]
</Location>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
