## {{ ansible_managed }}

[WebService]
Origins = https://{{ role_name }}.{{ domain }} wss://{{ role_name }}.{{ domain }}
ProtocolHeader = X-Forwarded-Proto
ForwardedForHeader = X-Forwarded-For
AllowUnencrypted = true
