## {{ ansible_managed }}

ProxyPass "/" "https://[::1]:{{ http_port }}/"
ProxyPassReverse "/" "https://[::1]:{{ http_port }}/"

ProxyPreserveHost On
RequestHeader set X-Forwarded-Proto 'https' env=HTTPS
RequestHeader set X-Forwarded-Host '{{ site_name | default(role_name) }}.{{ domain }}'

# Eh, can't seem to disable TLS in Cockpit, so disable cert checking
# of Cockpit's own certificates
SSLProxyEngine On
SSLProxyVerify None
SSLProxyCheckPeerCN Off
SSLProxyCheckPeerName Off
SSLProxyCheckPeerExpire Off

# Allow for upgrading to websockets
RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*)           wss://[::1]:{{ http_port }}/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule /(.*)           https://[::1]:{{ http_port }}/$1 [P,L]

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
