# When including these tasks into a role, the following variables are
# available:
#
# - record.name: set to override the default of "{{ role_name }}.{{ domain }}"
# - record.type: set the type of record, e.g. CNAME or SRV
# - record.text: set the value of the record, either a string or list of strings

- name: "DNS - Add {{ record.type | default('CNAME') }} Record to the Zone"
  community.general.nsupdate:
    key_name: "{{ ddns_secret_name }}"
    key_algorithm: "{{ ddns_secret_algo }}"
    key_secret: "{{ ddns_secret }}"
    server: "{{ host.ipv6.address }}"
    port: "{{ bind9_port }}"
    record: "{{ record.name | default(role_name + '.' + domain) }}."
    type: "{{ record.type | default('CNAME') }}"
    value: "{{ record.text }}"
    state: present
