# When including these tasks into a role, the following variables are
# available:
#
# - dns_record: set the FQDN of the A/AAAA record to add to the zone

- name: "DNS - Configure A/AAAA Records For {{ dns_record }}"
  ansible.builtin.include_tasks:
    file: ../../dns/tasks/configure-record.yml
  loop:
    - name: "{{ dns_record }}"
      type: A
      text: "{{ host.ipv4.address }}"
    - name: "{{ host.ipv4.address | ip_ptr }}"
      type: PTR
      text: "{{ dns_record }}."
    - name: "{{ dns_record }}"
      type: AAAA
      text: "{{ host.ipv6.address }}"
    - name: "{{ host.ipv6.address | ip_ptr }}"
      type: PTR
      text: "{{ dns_record }}."
  loop_control:
    loop_var: record
