# When including these tasks into a role, the following variables are
# available:
#
# - record.name: set to override the default value of "role_name"
# - record.type: set to override the default value of "CNAME"
# - record.text: set to override the default value of "host.fqdn"

- name: DNS - Determine if Record Exists
  ansible.builtin.command:
    cmd: "dig @{{ host.ipv4.address }} -p {{ bind9_port }} {{ record.name | default(role_name) }}.{{ domain }} {{ record.type | default('CNAME') }} +short"
  register: dns_lookup
  changed_when: False

- name: DNS - Add Record to the Zone
  ansible.builtin.command:
    cmd: "nsupdate -k /etc/named/dhcp-ddns.key -p {{ bind9_port }}"
    stdin: |
      server {{ host.fqdn }}
      update add {{ record.name | default(role_name) }}.{{ domain }} 14400 IN {{ record.type | default('CNAME') }} {{ record.text | default(host.fqdn) }}
      send
  when: not dns_lookup.stdout
