# When including these tasks into a role set the "cname" variable to
# override the default value of "role_name"

- name: Add CNAME Record to the DNS Zone
  ansible.builtin.command:
    cmd: "nsupdate -k /etc/named/dhcp-ddns.key"
    stdin: |
      update add {{ cname | default(role_name) }}.{{ domain }} 14400 IN CNAME {{ host.fqdn }}
      send
