# When including these tasks into a role, the following variables are
# available:
#
# - record: FQDN of the A/AAAA record to add to the zone

- name: DNS - Determine if A Record Exists
  ansible.builtin.command:
    cmd: "dig @{{ host.ipv4.address }} -p {{ bind9_port }} {{ record }} A +short"
  register: dns_a_lookup
  changed_when: False

- name: DNS - Add A Record to the Zone
  ansible.builtin.command:
    cmd: "nsupdate -k /etc/named/dhcp-ddns.key -p {{ bind9_port }}"
    stdin: |
      server {{ host.fqdn }}

      update add {{ record }}. 14400 IN A {{ host.ipv4.address }}

      update add {{ host.ipv4.address | ip_ptr }} 14400 IN PTR {{ record }}.

      send
  when: not dns_a_lookup.stdout

- name: DNS - Determine if AAAA Record Exists
  ansible.builtin.command:
    cmd: "dig @{{ host.ipv6.address }} -p {{ bind9_port }} {{ record }} AAAA +short"
  register: dns_aaaa_lookup
  changed_when: False

- name: DNS - Add AAAA Record to the Zone
  ansible.builtin.command:
    cmd: "nsupdate -k /etc/named/dhcp-ddns.key -p {{ bind9_port }}"
    stdin: |
      server {{ host.fqdn }}

      update add {{ record }}. 14400 IN AAAA {{ host.ipv6.address }}

      update add {{ host.ipv6.address | ip_ptr }} 14400 IN PTR {{ record }}.

      send
  when: not dns_a_lookup.stdout

