- name: Install BIND
  ansible.builtin.dnf:
    name:
      - bind
      - bind-utils
    state: present

- name: Allow BIND to Modify Files in the DB Root
  community.general.sefcontext:
    target: "{{ data_dir }}(/.*)?"
    setype: named_zone_t
    state: present

- name: Create BIND Data Directory
  ansible.builtin.file:
    state: directory
    setype: "{{ item.setype }}"
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ data_dir | dirname }}", setype: var_t, mode: '0755', owner: root, group: root }
    - { path: "{{ data_dir }}", setype: named_zone_t, mode: '0770', owner: root, group: named }

# This ensures the FQDN is correctly set and "hostname -f" gives the right
# answer
- name: Update Hosts File
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  loop:
    - "{{ host.ipv4.bond_ip }} {{ host.fqdn }} {{ host.name }}"
    - "{{ host.ipv6.bond_ip }} {{ host.fqdn }} {{ host.name }}"

# Ensure the host name is set correctly based on the inventory host on which
# we're being run
- name: Set Host Name
  ansible.builtin.hostname:
    name: "{{ host.name }}"
    use: systemd

# Disable systemd resolver features in favour of using the configured DNS
# resolvers directly
- name: Disable Unneeded Local Resolver Features
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '{{ item }}=.*'
    line: '{{ item }}=no'
  loop:
    - DNSStubListener
    - LLMNR
    - MulticastDNS
  notify:
    - Restart Resolver

- name: Set SELinux Context for Non-Standard DNS Port
  community.general.seport:
    ports: 5335
    proto: "{{ item }}"
    setype: dns_port_t
    state: present
  loop:
    - tcp
    - udp

- name: Install Main DNS Configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: named
    setype: named_conf_t
    mode: '0640'
  loop:
    - { src: named.conf, dest: /etc/named.conf }
    - { src: named.domains.conf, dest: /etc/named/domains.conf }
  notify:
    - Reload BIND DNS

- name: Generate DNS Zone Update Keys
  ansible.builtin.shell: /usr/sbin/tsig-keygen -a hmac-sha256 dhcp-ddns > /etc/named/dhcp-ddns.key
  args:
    creates: /etc/named/dhcp-ddns.key
  notify:
    - Reload BIND DNS

- name: Set Permissions on DNS Zone Update Keys
  ansible.builtin.file:
    path: /etc/named/dhcp-ddns.key
    owner: root
    group: named
    mode: '0640'

# Other roles may add records to the DNS zones, so we only need to install
# if not already present, instead of overwriting when different
- name: Checking For Installed DNS Zone Files
  ansible.builtin.stat:
    path: "{{ data_dir }}/{{ domain }}.zone"
  register: zone_config

- name: Install DNS Zone Configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ data_dir }}/{{ item.dest }}"
    owner: root
    group: named
    mode: '0640'
  loop:
    - { src: "forward.zone", dest: "{{ domain }}.zone" }
    - { src: "reverse4.zone", dest: "{{ host.ipv4.bond | ip_ptr }}.zone" }
    - { src: "reverse6.zone", dest: "{{ host.ipv6.bond | ip_ptr }}.zone" }
  when:
    - not zone_config.stat.exists
  notify:
    - Reload BIND DNS

- name: Ensure BIND DNS Service Overrides Directory
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/named.service.d
    mode: '0755'

- name: Install BIND DNS Service Overrides
  ansible.builtin.template:
    src: named.override.conf
    dest: "/etc/systemd/system/named.service.d/override.conf"
    mode: '0644'
  notify:
    - Reload BIND DNS

- name: Enable/Start BIND DNS
  ansible.builtin.systemd_service:
    name: named.service
    enabled: true
    masked: no
    state: started
