- name: Install BIND
  ansible.builtin.dnf:
    name:
      - bind
      - bind-utils
    state: present

# This ensures the FQDN is correctly set and "hostname -f" gives the right
# answer
- name: Update Hosts File
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  loop:
    - "{{ host.ipv4.address }} {{ host.fqdn }} {{ host.name }}"
    - "{{ host.ipv6.address }} {{ host.fqdn }} {{ host.name }}"

# Ensure the host name is set correctly based on the inventory host on which
# we're being run
- name: Set Host Name
  ansible.builtin.hostname:
    name: "{{ host.fqdn }}"
    use: systemd

- name: Ensure Local Resolver Config Directory
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/resolved.conf.d
    mode: '0755'

# Disable systemd resolver features in favour of using the configured DNS
# resolvers directly
- name: Disable Unneeded Local Resolver Features
  ansible.builtin.copy:
    src: 99-resolved.conf
    dest: /etc/systemd/resolved.conf.d/99-resolved.conf
  notify:
    - Restart Resolver

- name: Set SELinux Context for Non-Standard DNS Port
  community.general.seport:
    ports: "{{ bind9_port }}"
    proto: "{{ item }}"
    setype: dns_port_t
    state: present
  loop:
    - tcp
    - udp

- name: Install Main DNS Configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: named
    setype: named_conf_t
    mode: '0640'
  loop:
    - { src: named.conf, dest: /etc/named.conf }
    - { src: named.domains.conf, dest: /etc/named/domains.conf }
  notify:
    - Reload BIND DNS

- name: Generate DNS Zone Update Keys
  ansible.builtin.shell: /usr/sbin/tsig-keygen -a hmac-sha256 dhcp-ddns > /etc/named/dhcp-ddns.key
  args:
    creates: /etc/named/dhcp-ddns.key
  notify:
    - Reload BIND DNS

- name: Set Permissions on DNS Zone Update Keys
  ansible.builtin.file:
    path: /etc/named/dhcp-ddns.key
    owner: root
    group: named
    mode: '0640'

# Other roles may add records to the DNS zones, so we only need to install
# if not already present, instead of overwriting when different
- name: Checking For Installed DNS Zone Files
  ansible.builtin.stat:
    path: "/var/named/{{ domain }}.zone"
  register: zone_config

- name: Install DNS Zone Configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/var/named/{{ item.dest }}"
    owner: root
    group: named
    mode: '0640'
  loop:
    - { src: "forward.zone", dest: "{{ domain }}.zone" }
    - { src: "reverse4.zone", dest: "{{ host.ipv4.cidr | ip_ptr }}.zone" }
    - { src: "reverse6.zone", dest: "{{ host.ipv6.cidr | ip_ptr }}.zone" }
  when:
    - not zone_config.stat.exists
  notify:
    - Reload BIND DNS

- name: Ensure DNS Service Overrides Directory
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/named.service.d
    mode: '0755'

- name: Install DNS Service Overrides
  ansible.builtin.template:
    src: named.override.conf
    dest: "/etc/systemd/system/named.service.d/override.conf"
    mode: '0644'
  notify:
    - Reload BIND DNS

- name: Enable/Start DNS
  ansible.builtin.systemd_service:
    name: named.service
    enabled: true
    masked: no
    state: started

- name: Open Firewall for DNS
  ansible.posix.firewalld:
    service: dns
    permanent: true
    state: enabled
  notify:
    - Reload Firewall
