- name: Configure Apache for Jenkins
  ansible.builtin.include_tasks:
    file: ../../apache/tasks/configure-site.yml
  vars:
    site_proxy: true

- name: Import GPG Key for Jenkins Repository
  ansible.builtin.rpm_key:
    key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key
    state: present

- name: Enable Jenkins Repository
  ansible.builtin.copy:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: '0644'

- name: Install Jenkins
  ansible.builtin.dnf:
    name:
      - fontconfig
      - java-21-openjdk-headless
      - jenkins
    state: present

- name: Install Jenkins Configuration
  ansible.builtin.template:
    src: jenkins.model.JenkinsLocationConfiguration.xml
    dest: "/var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml"
    mode: '0644'

- name: Ensure Jenkins Service Overrides Directory
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/jenkins.service.d
    mode: '0755'

- name: Install Jenkins Service Overrides
  ansible.builtin.template:
    src: jenkins.override.conf
    dest: "/etc/systemd/system/jenkins.service.d/override.conf"
    mode: '0644'
  notify:
    - Restart Jenkins

- name: Enable/Start Jenkins
  ansible.builtin.systemd_service:
    name: jenkins.service
    enabled: true
    masked: no
    state: started

#- name: Install Jenkins Plugins
#  community.general.jenkins_plugin:
#    name: "{{ item }}"
#  loop:
#    - ant
#    - gradle
#    - maven-plugin
#    - git
#    - git-parameter
#    - github
#    - gitlab-plugin
#    - build-name-setter
