- name: Install Podman
  ansible.builtin.dnf:
    name:
      - podman
    state: present

- name: Enable/Start Podman
  ansible.builtin.systemd_service:
    name: podman.socket
    enabled: true
    masked: no
    state: started
