- name: Import GPG Key for Jenkins Repository
  ansible.builtin.rpm_key:
    key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key
    state: present

- name: Enable Jenkins Repository
  ansible.builtin.copy:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: '0644'

- name: Install Jenkins
  ansible.builtin.dnf:
    name:
      - git
      - fontconfig
      - java-21-openjdk-headless
      - jenkins
    state: present

- name: Configure Apache for Jenkins
  ansible.builtin.include_tasks:
    file: ../../http/tasks/configure-site.yml
  vars:
    site_proxy: true
    http_port: "{{ jenkins_http_port }}"

- name: Configure Keycloak for Jenkins
  ansible.builtin.include_tasks:
    file: ../../id/tasks/configure-client.yml
  vars:
    client:
      name: "Jenkins"
      description: "Continuous Integration"
      secret: "{{ jenkins_secret }}"
      redirect_uris: [ "/securityRealm/finishLogin" ]
      logout_uri: "/OicLogout"

- name: Ensure Jenkins Service Overrides Directory
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/jenkins.service.d
    mode: '0755'

- name: Install Jenkins Service Overrides
  ansible.builtin.template:
    src: jenkins.override.conf
    dest: "/etc/systemd/system/jenkins.service.d/override.conf"
    mode: '0644'
  notify:
    - Restart Jenkins

- name: Enable/Start Jenkins
  ansible.builtin.systemd_service:
    name: jenkins.service
    enabled: true
    masked: no
    state: started

# Jenkins can take a minute to come up and it needs to be online for the next steps
- name: Wait On Jenkins Start
  ansible.builtin.wait_for:
    host: "::1"
    port: "{{ jenkins_http_port }}"

- name: Install Jenkins Plugins
  community.general.jenkins_plugin:
    name: "{{ item }}"
    url: "http://[::1]:{{ jenkins_http_port }}"
    state: present
  loop:
    # Admin / Security
    - dark-theme
    - dashboard-view
    - cloudbees-folder
    - configuration-as-code
    - antisamy-markup-formatter
    - oic-auth
    - matrix-auth
    - role-strategy
    # Build tools
    - ant
    - gradle
    - maven-plugin
    # Source control
    - git
    - git-parameter
    - github
    - gitlab-plugin
    # Build features
    - build-name-setter
    - build-timeout
    - embeddable-build-status
    - ssh-agent
    - throttle-concurrents
    - timestamper
    - ws-cleanup
    # Distributed builds
    - docker-plugin
    - libvirt-slave
    - ssh-slaves
    # Notifications
    - email-ext
    - emailext-template
    - mailer
  notify:
    - Restart Jenkins

- name: Install Jenkins Configuration
  ansible.builtin.template:
    src: jenkins.yaml
    dest: /var/lib/jenkins/jenkins.yaml
    group: jenkins
    mode: '0640'
  notify:
    - Restart Jenkins

