## {{ ansible_managed }}

Alias /ui /usr/share/ipsilon/ui
Alias /.well-known /var/lib/ipsilon/root/public/well-known
Alias /cache /var/cache/ipsilon
Redirect /.well-known/webfinger /webfinger

WSGIScriptAlias / /usr/libexec/ipsilon/ipsilon
WSGIDaemonProcess {{ role_name }} user=ipsilon group=ipsilon home=/var/lib/ipsilon/root display-name=ipsilon-{{ role_name }}

# Without this, getting the private key in jwcrypto/jwk.py, line 430, fails
# Fix from https://github.com/pyca/cryptography/issues/2299#issuecomment-197075190
WSGIApplicationGroup %{GLOBAL}

<Location />
	WSGIProcessGroup {{ role_name }}
</Location>

<Directory "/usr/libexec/ipsilon">
	Require all granted
</Directory>

<Directory "/usr/share/ipsilon">
	Options +SymLinksIfOwnerMatch
	Require all granted
</Directory>

<Directory "/var/lib/ipsilon/root/public/well-known">
	Require all granted
</Directory>

<Location /.well-known/browserid>
	ForceType application/json
</Location>

<Directory "/var/cache/ipsilon">
	SetHandler None
	AllowOverride None
	Require all granted
</Directory>

<Location /login/gssapi/negotiate>
	AuthName "Single Sign On"
	<IfModule mod_auth_gssapi.c>
		GssapiCredStore keytab:/etc/httpd/http.keytab
		AuthType GSSAPI
		GssapiSSLonly On
		GssapiLocalName On
	</IfModule>
	Require valid-user

	ErrorDocument 401 /login/gssapi/unauthorized
	ErrorDocument 500 /login/gssapi/failed
</Location>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
