interface bond0
{
        AdvSendAdvert on;
        MinRtrAdvInterval 60;
        MaxRtrAdvInterval 600;
        AdvDefaultPreference high;
        AdvHomeAgentFlag off;
        AdvManagedFlag on;
        AdvOtherConfigFlag on;
        AdvReachableTime 0;
        AdvRetransTimer 0;
        AdvCurHopLimit 64;
        AdvDefaultLifetime 1800;
        AdvSourceLLAddress on;
        AdvLinkMTU 1500;
        AdvIntervalOpt on;

        prefix {{ host.ipv6.subnet }}
        {
                AdvValidLifetime 5400;
                AdvPreferredLifetime 5400;
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr off;
        }; # End of prefix definition

        route {{ host.ipv6.network }}/48
        {
                AdvRoutePreference medium;
                AdvRouteLifetime 1800;
        }; # End of route definition

}; # End of interface definition
