interface bridge0
{
        AdvSendAdvert on;
        MinRtrAdvInterval 60;
        MaxRtrAdvInterval 600;
        AdvDefaultPreference high;
        AdvHomeAgentFlag off;
        AdvManagedFlag off;
        AdvOtherConfigFlag on;
        AdvReachableTime 0;
        AdvRetransTimer 0;
        AdvCurHopLimit 64;
        AdvDefaultLifetime 1800;
        AdvSourceLLAddress on;
        AdvLinkMTU 1500;
        AdvIntervalOpt on;

        prefix {{ host.subn6 }}
        {
                AdvValidLifetime 6843;
                AdvPreferredLifetime 6843;
                AdvOnLink on;
                AdvAutonomous on;
                AdvRouterAddr off;
        }; # End of prefix definition


        route {{ host.subn6 }}
        {
                AdvRoutePreference medium;
                AdvRouteLifetime 1200;
        }; # End of route definition


        RDNSS {{ host.addr6 }}
        {
                AdvRDNSSLifetime 1200;
        }; # End of RDNSS definition


        DNSSL {{ domain }}
        {
                AdvDNSSLLifetime 1200;
        }; # End of DNSSL definition

}; # End of interface definition
