## {{ ansible_managed }}

<VirtualHost *:80>
{% if site_name | default(role_name) != 'default' %}
	ServerName {{ site_name | default(role_name) }}.{{ domain }}
{% endif %}

{% if site_name | default(role_name) != 'default' %}
	ErrorLog "logs/{{ site_name | default(role_name) }}_error_log"
	CustomLog "logs/{{ site_name | default(role_name) }}_access_log" combined
{% endif %}

	# The well-known URLs for certbot/letsencrypt
	AliasMatch "^/(.well-known/acme-challenge/.*)" "/usr/share/certbot/$1"

	# Redirect all URLs to their HTTPS equivilents except the well-known
	# URLs used for certbot/letsencrypt
	RewriteEngine on
	RewriteRule ^/((?!\.well-known/acme-challenge/).*)$ https://%{HTTP_HOST}/$1 [R=307]
</VirtualHost>

<VirtualHost _default_:443>
{% if site_name | default(role_name) != 'default' %}
	ServerName {{ site_name | default(role_name) }}.{{ domain }}
{% endif %}

{% if site_name | default(role_name) != 'default' %}
	ErrorLog "logs/{{ site_name | default(role_name) }}_error_log"
	CustomLog "logs/{{ site_name | default(role_name) }}_access_log" combined
{% endif %}

	SSLEngine on
	SSLHonorCipherOrder on
	SSLCipherSuite PROFILE=SYSTEM
	SSLProxyCipherSuite PROFILE=SYSTEM
	SSLCertificateFile /etc/letsencrypt/live/{{ srv_fqdn }}/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/{{ srv_fqdn }}/privkey.pem
	<FilesMatch "\.(cgi|shtml|phtml|php)$">
		SSLOptions +StdEnvVars
	</FilesMatch>

	# Include site-specific configuration
	IncludeOptional conf.d/includes.d/{{ site_name | default(role_name) }}/*.conf
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
