## {{ ansible_managed }}

DocumentRoot "{{ www_root }}/{{ site_name | default(role_name) }}"

<Directory "{{ www_root }}/{{ site_name | default(role_name) }}">
	Options Indexes FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
