configuration-as-code: {
  }
credentials:
  folder: {
    }
  providerImpl: {
    }
  system:
    domainCredentials:
    - domain: {
        }
  user: {
    }
jenkins:
  authorizationStrategy:
    globalMatrix:
      entries:
      - user:
          name: "anonymous"
          permissions:
          - "Job/Read"
          - "Overall/Read"
      - group:
          name: "authenticated"
          permissions:
          - "Job/Read"
          - "Overall/Read"
          - "View/Read"
      - group:
          name: "jenkins_admins"
          permissions:
          - "Overall/Administer"
      - group:
          name: "jenkins_users"
          permissions:
          - "Agent/Build"
          - "Agent/Configure"
          - "Agent/Connect"
          - "Agent/Create"
          - "Agent/Delete"
          - "Agent/Disconnect"
          - "Agent/Provision"
          - "Credentials/Create"
          - "Credentials/Delete"
          - "Credentials/ManageDomains"
          - "Credentials/Update"
          - "Credentials/View"
          - "Job/Build"
          - "Job/Cancel"
          - "Job/Configure"
          - "Job/Create"
          - "Job/Delete"
          - "Job/Discover"
          - "Job/Move"
          - "Job/Read"
          - "Job/ViewStatus"
          - "Job/Workspace"
          - "Overall/Read"
          - "Run/Delete"
          - "Run/Replay"
          - "Run/Update"
          - "SCM/Tag"
          - "View/Configure"
          - "View/Create"
          - "View/Delete"
          - "View/Read"
  clouds:
  - hypervisor:
      hypervisorHost: ""
      hypervisorSshPort: 0
      hypervisorSystemUrl: "system"
      hypervisorTransport: "unix"
      hypervisorType: "QEMU"
      maxOnlineSlaves: 2
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "hudson.util.DoubleLaunchChecker"
  labelAtoms:
  - name: "built-in"
  log: {
    }
  markupFormatter: "plainText"
  mode: NORMAL
  nodeMonitors:
  - "architecture"
  - "clock"
  - diskSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "swapSpace"
  - tmpSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "responseTime"
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    oic:
      clientId: "jenkins"
      clientSecret: "{{ jenkins_secret }}"
      disableSslVerification: false
      emailFieldName: "email"
      fullNameFieldName: "display_name"
      groupIdStrategy: "caseSensitive"
      groupsFieldName: "groups"
      postLogoutRedirectUrl: "https://{{ role_name }}.{{ domain }}/OicLogout"
      serverConfiguration:
        wellKnown:
          scopesOverride: "openid profile email"
          wellKnownOpenIDConfigurationUrl: "https://id.{{ domain }}/realms/{{ domain }}/.well-known/openid-configuration"
      userIdStrategy: "caseSensitive"
      userNameField: "preferred_username"
  slaveAgentPort: 0
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  consoleUrlProvider: {
    }
  prism:
    theme: PRISM
  themeManager:
    disableUserThemes: false
    theme: "darkSystem"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  apiTokenProperty: {
    }
  cps:
    hideSandbox: false
  crumb: {
    }
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  prism: {
    }
  queueItemAuthenticator: {
    }
  scriptApproval:
    forceSandbox: false
  updateSiteWarningsConfiguration: {
    }
unclassified:
  administrativeMonitorsConfiguration: {
    }
  artifactManager: {
    }
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  builtInNode: {
    }
  casCGlobalConfig: {
    }
  computerRetentionCheckInterval: {
    }
  defaultDisplayUrlProvider: {
    }
  defaultFolderConfiguration: {
    }
  defaultView: {
    }
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    mailAccount:
      smtpHost: "smtp.aa.net.uk"
      smtpPort: "587"
      useTls: true
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    throttlingEnabled: false
    watchingEnabled: false
  enrichedSummaryConfig:
    enrichedSummaryEnabled: false
    httpClientDelayBetweenRetriesInSeconds: 1
    httpClientMaxRetries: 3
    httpClientTimeoutInSeconds: 1
  envVarsFilter: {
    }
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubPluginConfig:
    hookUrl: "https://{{ role_name }}.{{ domain }}/github-webhook/"
  gitLabConnectionConfig:
    connections:
    - clientBuilderId: "autodetect"
      connectionTimeout: 10
      ignoreCertificateErrors: false
      readTimeout: 10
    useAuthenticatedEndpoint: true
  gitParameter: {
    }
  globalDefaultFlowDurabilityLevel: {
    }
  globalTimeOutConfiguration:
    operations:
    - "abortOperation"
    overwriteable: false
  injectionConfig:
    allowUntrusted: false
    checkForBuildAgentErrors: false
    enabled: false
    enforceUrl: false
    gradleCaptureTaskInputFiles: true
    injectCcudExtension: false
    injectMavenExtension: false
    mavenCaptureGoalInputFiles: true
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "Jenkins <jenkins@{{ domain }}>"
    url: "https://{{ role_name }}.{{ domain }}/"
  mailer:
    charset: "UTF-8"
    smtpHost: "smtp.aa.net.uk"
    smtpPort: "587"
    useSsl: false
    useTls: true
  mavenModuleSet:
    localRepository: "default"
  myView: {
    }
  nodeProperties: {
    }
  plugin: {
    }
  pollSCM:
    pollingThreadCount: 10
  projectNamingStrategy: {
    }
  proxyConfigurationManager: {
    }
  quietPeriod: {
    }
  resourceRoot: {
    }
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  scmRetryCount: {
    }
  shell: {
    }
  throttleJobProperty: {
    }
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
  usageStatistics: {
    }
  viewsTabBar: {
    }
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
