---
- name: Restart KDC
  ansible.builtin.systemd_service:
    name: krb5kdc.service
    daemon_reload: true
    state: restarted

- name: Restart KAdmin
  ansible.builtin.systemd_service:
    name: kadmin.service
    daemon_reload: true
    state: restarted
