## {{ ansible_managed }}

# Disallow simple password auth, but allow these auth methods:
# - Public key
# - GSSAPI (aka Kerberos)
# - Complex keyboard interactive (e.g. password + OTP token)

PasswordAuthentication no

PubkeyAuthentication yes

GSSAPIAuthentication yes
GSSAPICleanupCredentials no

KbdInteractiveAuthentication yes

UsePAM yes
