- name: Install PostgreSQL
  ansible.builtin.dnf:
    name:
      - postgresql-server
      - python3-psycopg2
    state: present

- name: Allow PostgreSQL to Modify Files in the DB Root
  community.general.sefcontext:
    target: "{{ data_dir }}(/.*)?"
    setype: postgresql_db_t
    state: present

- name: Create PostgreSQL Data Directory
  ansible.builtin.file:
    state: directory
    setype: "{{ item.setype }}"
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ data_dir | dirname }}", setype: var_t, mode: '0755', owner: root }
    - { path: "{{ data_dir }}", setype: postgresql_db_t, mode: '0700', owner: postgres }

- name: Ensure PostgreSQL  Service Overrides Directory
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/postgresql.service.d
    mode: '0755'

- name: Install PostgreSQL Service Overrides
  ansible.builtin.template:
    src: postgresql.override.conf
    dest: "/etc/systemd/system/postgresql.service.d/override.conf"
    mode: '0644'
  notify:
    - Restart PostgreSQL

- name: Initialise PostgreSQL
  ansible.builtin.command:
    cmd: postgresql-setup --initdb --unit postgresql
    creates: "{{ data_dir }}/pg_hba.conf"

- name: Install PostgreSQL Configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: postgres
    group: postgres
    mode: '0600'
  loop:
    - { src: postgresql.conf , dest: "{{ data_dir }}/postgresql.conf" }
    - { src: pg_hba.conf , dest: "{{ data_dir }}/pg_hba.conf" }
  notify:
    - Restart PostgreSQL

- name: Enable/Start PostgreSQL
  ansible.builtin.systemd_service:
    name: postgresql.service
    enabled: true
    masked: no
    state: started
