# This initial configuration is temporary until we get the DHCP and
# DNS services up, so only perform if there is no bonded connection
# or virtual bridge yet at all

- name: Create Bonded Connection
  community.general.nmcli:
    type: bond
    conn_name: bond0
    autoconnect: true
    mode: balance-alb
    state: present
  when: "'bond0' not in ansible_facts"

- name: Add Wired NICs to Bonded Connection
  community.general.nmcli:
    type: bond-slave
    ifname: "{{ item }}"
    conn_name: "{{ item }}"
    master: bond0
    state: present
  loop: "{{ ansible_interfaces }}"
  when: item.startswith('en')

- name: Create Virtual Network Bridge
  community.general.nmcli:
    type: bridge
    conn_name: bridge0
    autoconnect: true
    ip4: "{{ host.cidr4 }}"
    gw4: "{{ host.gate4 }}"
    dns4: "{{ host.gate4 }}"
    ip6: "{{ host.cidr6 }}"
    gw6: "{{ host.gate6 }}"
    dns6: "{{ host.gate6 }}"
    stp: true
    state: present
  when: "'bridge0' not in ansible_facts"

- name: Add Bonded Connection as a Port on the Virtual Network Bridge
  community.general.nmcli:
    type: bridge-slave
    ifname: bond0
    conn_name: bond0
    master: bridge0
    hairpin: true
    state: present

# Bit overkill, but I couldn't figure out how to bring up the bonded
# connection/virtual bridge without killing Ansible's SSH connection

- name: Reboot Machine
  ansible.builtin.reboot:
    msg: "Rebooting to bring up bonded network connection"
  when: "'bond0' not in ansible_facts or 'bridge0' not in ansible_facts"

- name: Regather Facts About the New Network Connections
  ansible.builtin.setup:
  when: "'bond0' not in ansible_facts or 'bridge0' not in ansible_facts"
