- name: Create Temporary Directory
  ansible.builtin.file:
    path: /tmp/.ansible-maint
    state: directory
    recurse: yes
    owner: root
    group: wheel
    mode: '0770'

- name: Configure TPM2 for Automatic LUKS Volume Decryption
  ansible.builtin.include_tasks:
    file: configure-luks-tpm2.yml

- name: Configure Ansible User
  ansible.builtin.include_tasks:
    file: configure-ansible-user.yml

- name: Switch Default Editor
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop:
    - { name: [ nano-default-editor, nano ], state: absent }
    - { name: vim-default-editor, state: present }
