- name: Create Bonded Network Connection with Static IP
  community.general.nmcli:
    type: bond
    conn_name: bond0
    autoconnect: true
    ip4: "{{ host_ip }}/24"
    gw4: "{{ host_gw }}"
    dns4: "{{ host_dns }}"
    mode: balance-alb
    state: present

- name: Add Wired NICs to Bonded Network Connection
  community.general.nmcli:
    type: bond-slave
    ifname: "{{ item }}"
    conn_name: "{{ item }}"
    master: bond0
    state: present
  loop: "{{ ansible_interfaces }}"
  when: "item.startswith('en')"

- name: Set Host Name
  ansible.builtin.hostname:
    name: "{{ host_name }}"
    use: systemd

- name: Update Hosts File
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ host_ip }} {{ host_fqdn }} {{ host_name }}"

# Bit overkill, but I couldn't figure out how to bring up the
# connection without interrupting Ansible's SSH connection
- name: Reboot Machine
  ansible.builtin.reboot:
    msg: "Rebooting to bring up bonded network connection"

- name: Add Ansible Group
  ansible.builtin.group:
    name: ansible-maint
    state: present
    system: true

- name: Add Ansible User
  ansible.builtin.user:
    name: ansible-maint
    comment: Ansible Maintenance
    state: present
    system: true
    append: true
    home: /
    create_home: false
    group: ansible-maint
    groups: wheel
    password: '!'
    password_lock: true

- name: Ensure Authorized Keys Directory
  ansible.builtin.file:
    path: /etc/authorized_keys
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install SSH Public Key for Ansible
  ansible.posix.authorized_key:
    user: ansible-maint
    state: present
    path: /etc/ssh/authorized_keys/ansible-maint
    manage_dir: false
    key: "{{ lookup('file', '~/.ssh/id_home.pub') }}"

- name: Install Sudoers Configuration for Ansible
  ansible.builtin.copy:
    src: sudoers
    dest: "/etc/sudoers.d/ansible-maint"
    mode: '0440'

- name: Install SSHd Configuration
  ansible.builtin.copy:
    src: sshd.conf
    dest: "/etc/ssh/sshd_config.d/99-{{ domain }}.conf"
    mode: '0600'
  notify:
    - Reload SSHd

- name: Switch Default Editor
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop:
    - { name: [ nano-default-editor, nano ], state: absent }
    - { name: vim-default-editor, state: present }

- name: Reset Ownership of Temporary Directory
  ansible.builtin.file:
    path: /tmp/.ansible
    state: directory
    recurse: yes
    owner: ansible-maint
    group: ansible-maint

