## {{ ansible_managed }}

<VirtualHost *:80>
	ServerName {{ _site }}.{{ domain }}

	ErrorLog "logs/{{ _site }}_error_log"
	CustomLog "logs/{{ _site }}_access_log" combined

	# The well-known URLs for certbot/letsencrypt
	AliasMatch "^/(.well-known/acme-challenge/.*)" "{{ www_root }}/acme/$1"

	# Redirect all URLs to their HTTPS equivilents except the well-known
	# URLs used for certbot/letsencrypt
	RewriteEngine on
	RewriteRule ^/((?!\.well-known/acme-challenge/).*)$ https://%{HTTP_HOST}/$1 [R=307]
</VirtualHost>

<VirtualHost _default_:443>
	ServerName {{ _site }}.{{ domain }}

	ErrorLog "logs/{{ _site }}_error_log"
	CustomLog "logs/{{ _site }}_access_log" combined

	SSLEngine on
	SSLHonorCipherOrder on
	SSLCipherSuite PROFILE=SYSTEM
	SSLProxyCipherSuite PROFILE=SYSTEM
	SSLCertificateFile /etc/letsencrypt/live/{{ _site }}.{{ domain }}/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/{{ _site }}.{{ domain }}/privkey.pem
	<FilesMatch "\.(cgi|shtml|phtml|php)$">
		SSLOptions +StdEnvVars
	</FilesMatch>

	# Include site-specific configuration
	IncludeOptional conf.d/includes.d/{{ _site }}/*.conf
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
