## {{ ansible_managed }}

# Default "catch-all" virtual host configuration
# Redirects all traffic to the home page for any unrecognised server names

<VirtualHost *:80>
	# The well-known URLs for certbot/letsencrypt
	AliasMatch "^/(.well-known/acme-challenge/.*)" "{{ www_root }}/acme/$1"

	# Redirect everything except the well-known URLs used for certbot/letsencrypt
	RewriteEngine on
	RewriteRule ^/((?!\.well-known/acme-challenge/).*)$ https://{{ domain }}/ [R=307]
</VirtualHost>

<VirtualHost _default_:443>
	SSLEngine on
	SSLHonorCipherOrder on
	SSLCipherSuite PROFILE=SYSTEM
	SSLProxyCipherSuite PROFILE=SYSTEM
	SSLCertificateFile /etc/letsencrypt/live/{{ host.name }}.{{ domain }}/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/{{ host.name }}.{{ domain }}/privkey.pem

	# Redirect everything
	RewriteEngine on
	RewriteRule ^/(.*)$ https://{{ domain }}/ [R=307]
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
