## {{ ansible_managed }}

ProxyPass "/" "http://[::1]:{{ http_port }}/" upgrade=websocket
ProxyPassReverse "/" "http://[::1]:{{ http_port }}/"
ProxyRequests Off
ProxyPreserveHost On
RequestHeader set X-Forwarded-Proto 'https' env=HTTPS

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
