## {{ ansible_managed }}

# Encrypted default "catch-all" virtual host configuration
# All traffic to port 443 bound for any unrecognised server names hits this
<VirtualHost _default_:443>
	SSLEngine on
	SSLHonorCipherOrder on
	SSLCipherSuite PROFILE=SYSTEM
	SSLProxyCipherSuite PROFILE=SYSTEM
	SSLCertificateFile /etc/letsencrypt/live/{{ host.name }}.{{ domain }}/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/{{ host.name }}.{{ domain }}/privkey.pem

	# Blanket redirect everything to the static home page
	RewriteEngine on
	RewriteRule ^/(.*)$ https://{{ domain }}/ [R=307]
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
